title: Jianming Tong
description: PhD student at Georgia Tech
theme: jekyll-theme-minimal
srclink: https://github.com/JianmingTONG/JianmingTONG.github.io
logo: /images/profile.jpg
show_downloads: true
